server:
  port: 8098
spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema:
          registry:
            url: http://localhost:8081
app:
  kafka:
    topic:
      name: books